data_type: "custom_pt"
data_name: "diffusion_2moons"
dim: 2
whiten: false
#seeds: [0]
time_indices: [0, 5, -1]
t_exclude: null
gammas: [0.5]
mfm: false
velocity_metric: "land"
rho: 0.001
alpha_metric: 1
hidden_dims_flow: [64, 64, 64]
hidden_dims_geopath: [64, 64, 64]
patience: 20
patience_geopath: 20
epochs: 2000
batch_size: 128
optimal_transport_method: "exact"
accelerator: "gpu"
class_conditioning: true
categorical: true
cond_dim: 1
