data_type: "custom_pt"
data_name: "quantile_data_new"
dim: 3
whiten: false
#seeds: [0]
gammas: [0.01]
t_exclude: null
mfm: true
velocity_metric: "land"
rho: 0.001
alpha_metric: 1
hidden_dims_flow: [64, 64, 64]
hidden_dims_geopath: [64, 64, 64]
patience: 100
patience_geopath: 100
epochs: 2000
batch_size: 128
accelerator: "gpu"
class_conditioning: true
categorical: false
cond_dim: 12
instance_paired: true
ema_decay: 0.9999



