model_path: "exp/local/2025.05.10/1421.neural_net_metric_eig/latest.pkl" 

evaluation_seed: 0

data_source: "pkl"  

eval_data_pkl_path: "eval_marginals_semicircle.pkl"

num_evaluation_time_points: 3
num_samples_per_time_point: 400
evaluation_time_points_values: [0, 0.25,0.75]


data_generation_config:
  # 'type' corresponds to the 'name' parameter in lagrangian_ot.data.get_samplers_scarvelis
  type: "scarvelis_semicircle"
  # Specific parameters for the chosen 'type'. Examples for "scarvelis_semicircle":
  radius: 1.0
  angle_std_dev: 5.0 # Standard deviation of the angle in degrees for semicircle
  noise: 0.05         # General noise added to the points


plotting:
  plot_results: True   
  display_plots: False    

verbose_evaluation: False  

hydra:
  run:
    dir: ./outputs/evaluate/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/evaluate/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

