defaults:
  - _self_

# neural_net_metric, neural_net_metric_eig, neural_net_metric_direct, land_metric, rbf_metric, 
# scarvelis_circle, scarvelis_xpath, scarvelis_vee, sq_euclidean_manifold
geometry: 'neural_net_metric_eig'

# scarvelis_circle, scarvelis_xpath, scarvelis_vee, scarvelis_arch, 
# scarvelis_conditional_gaussian, scarvelis_conditional_gaussian_complex, sphere_data, 
# agent_data, conditional_velocity, conditional_rotation, warped_circle, conditional_circles, 
# conditional_circles_normal, conditional_semicircles, reward_weighting_data, ett_forecasts
dataset: 'ett_forecasts'
D: 12
C: 24
categorical: False
num_categories: 4

include_inverse_potential: False
bandwidth: 1.0
conditional_bandwidth: 1.0
lambda: 0.01

seed: 0
num_pairs: 2
num_train_iters: 2001
batch_size: 1024
potential_lr: 1e-4
wandb: True
wandb_project: "ett_forecasts_NN"

plot_frequency: 50
save_frequency: ${plot_frequency}

plotting:
  disable: False
  num_pairs_plot: 100
  
metric:
  warmup_steps: 50
  update_frequency: 10
  update_repeat: 1
  frobenius_reg_weight: 0
  lr: 1e-4 #changed from 5e-3

geometry_kwargs:
  spline_solver_kwargs:
    num_spline_nodes: 15
    grad_tol: 1e-5
    init_lr: 1e-2
    num_spline_points_eval: 50
    max_iter: 0

ctransform_solver:
  _target_: lagrangian_ot.ctransform_solvers.CTransformLBFGS
  gtol: 1e-5
  max_iter: 3
  max_linesearch_iter: 20
  linesearch_type: "backtracking"

spline:
  init_train_iters: 1001
  train_iters: 1001
  update_frequency: 25
  grad_norm_threshold: 1e-4
  noise: 0.0
  update_on_conjugates: False

target_potential_dim_hidden: [64, 64, 64, 64]
source_map_dim_hidden: [64, 64, 64, 64]

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/${now:%H%M}.${geometry}
  job:
    chdir: True
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}
    subdir: ${hydra.job.num}
