defaults:
  - _self_

# neural_net_metric, scarvelis_circle, scarvelis_xpath, scarvelis_vee, neural_net_metric_eig, land_metric
geometry: 'land_metric'
data: 'scarvelis_circle'
num_pairs: 10 # Set to integer N to use N evenly spaced pairs, null to use all
seed: 1
num_train_iters: 2000
batch_size: 1024
potential_lr: 1e-4

plot_frequency: 50
save_frequency: ${plot_frequency}

land_kwargs:
  alpha: 1
  rho: 0.001
  gamma: 0.125
  
metric:
  warmup_steps: 50
  update_frequency: 10
  update_repeat: 1
  frobenius_reg_weight: 0
  lr: 5e-3
  
  
geometry_kwargs:
  spline_solver_kwargs:
    num_spline_nodes: 30
    grad_tol: 1e-5
    init_lr: 1e-2
    num_spline_points_eval: 20
    max_iter: 0


ctransform_solver:
  _target_: lagrangian_ot.ctransform_solvers.CTransformLBFGS
  gtol: 1e-5
  max_iter: 20
  max_linesearch_iter: 20
  linesearch_type: "backtracking"

spline:
  init_train_iters: 1001
  train_iters: 1001
  update_frequency: 25
  grad_norm_threshold: 1e-4
  noise: 0.0
  update_on_conjugates: True

target_potential_dim_hidden: [64, 64, 64, 64]
source_map_dim_hidden: [64, 64, 64, 64]

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/${now:%H%M}.${geometry}
  job:
    chdir: True
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}
    subdir: ${hydra.job.num}
