_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 12
                - 45
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 12
                - 45
                - 50
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
                - 13
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 1024
ctransform_solver:
    value:
        _target_: lagrangian_ot.ctransform_solvers.CTransformLBFGS
        gtol: 1e-05
        linesearch_type: backtracking
        max_iter: 20
        max_linesearch_iter: 20
data:
    value: scarvelis_xpath
geometry:
    value: scarvelis_circle
geometry_kwargs:
    value:
        spline_solver_kwargs:
            grad_tol: 1e-05
            init_lr: 0.01
            max_iter: 0
            num_spline_nodes: 30
            num_spline_points_eval: 20
metric:
    value:
        lr: 0.005
        update_frequency: 10
        update_repeat: 1
        warmup_steps: 50
num_train_iters:
    value: 3001
plot_frequency:
    value: 100
potential_lr:
    value: 0.0001
save_frequency:
    value: 100
seed:
    value: 0
source_map_dim_hidden:
    value:
        - 64
        - 64
        - 64
        - 64
spline:
    value:
        grad_norm_threshold: 0.0001
        init_train_iters: 1001
        noise: 0
        train_iters: 1001
        update_frequency: 25
        update_on_conjugates: true
target_potential_dim_hidden:
    value:
        - 64
        - 64
        - 64
        - 64
